{% set version = "2.77.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}
{% set sha256 = "7cb34684e7ac6dfbf83492a52dff3f919e2fff63eb7810613bf71eb272d5450e" %}
{% set abi_version = "2.68" %}

package:
  name: glibmm
  version: {{ version }}

source:
  fn: glibmm-{{ version }}.tar.xz
  url: https://download.gnome.org/sources/glibmm/{{ major_minor }}/glibmm-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - glibmm-{{ abi_version }} >={{ version }}

outputs:
  - name: glibmm-{{ abi_version }}
    script: build_glibmm.sh  # [unix]
    script: build_glibmm.bat  # [win]
    build:
      run_exports:
        - glibmm-{{ abi_version }} >={{ version }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - meson
        - ninja
        - pkg-config
      host:
        - sigcpp-3.0
        - glib
        - zlib
        - xz
      run_constrained:
        - glibmm {{ version }}
    test:
      requires:
        - pkg-config
        - glib
        - zlib
        - xz
      commands:
        - test -f ${PREFIX}/lib/libglibmm-{{ abi_version }}${SHLIB_EXT}  # [unix]
        - test -f ${PREFIX}/lib/libgiomm-{{ abi_version }}${SHLIB_EXT}  # [unix]
        - test -f ${PREFIX}/lib/libglibmm_generate_extra_defs-{{ abi_version }}${SHLIB_EXT}  # [unix]
        - if not exist %LIBRARY_BIN%\\glibmm-vc142-{{ abi_version }}-1.dll exit 1  # [win]
        - pkg-config --exact-version {{ version }} glibmm-{{ abi_version }}
        - pkg-config --exact-version {{ version }} giomm-{{ abi_version }}

  - name: glibmm
    requirements:
      run:
        - glibmm-{{ abi_version }}  {{ version }}
    test:
      commands:
        - test -f ${PREFIX}/lib/pkg-config/glibmm-{{ abi_version }}.pc  # [unix]
        - if not exist %LIBRARY_LIB%\\pkgconfig\\glibmm-{{ abi_version }}.pc exit 1  # [win]

about:
  home: http://www.gtkmm.org
  license: LGPL-2.1-or-later
  license_family: GPL
  license_file: COPYING
  summary: This is glibmm, a C++ API for parts of glib that are useful for C++.

extra:
  recipe-maintainers:
    - scopatz
    - isuruf
    - tschoonj
