{% set version = "2.58.1" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}
{% set sha256 = "6e5fe03bdf1e220eeffd543e017fd2fb15bcec9235f0ffd50674aff9362a85f0" %}

package:
  name: glibmm
  version: {{ version }}

source:
  fn: glibmm-{{ version }}.tar.xz
  url: http://ftp.gnome.org/pub/GNOME/sources/glibmm/{{ major_minor }}/glibmm-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - make
    - pkg-config
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libsigcpp 2.*
    - glib
    - xz
  run:
    - libsigcpp 2.*

test:
  commands:
    - test -f ${PREFIX}/lib/libgiomm-2.4${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libglibmm-2.4${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libglibmm_generate_extra_defs-2.4${SHLIB_EXT}

about:
  home: http://www.gtkmm.org
  license: LGPL-2.1-or-later
  license_family: GPL
  license_file: COPYING
  summary: "This is glibmm, a C++ API for parts of glib that are useful for C++."

extra:
  recipe-maintainers:
    - scopatz
    - isuruf
